window.GAME_DATA = {
  characters: [
    { id: "gabriel", name: "Gabriel", role: "玩家", note: "渴望被理解，却常用礼貌与知识保护自己。" },
    { id: "gretta", name: "Gretta", role: "妻子", note: "今夜似乎被某段遥远记忆牵引。" },
    { id: "lily", name: "Lily", role: "女佣", note: "敏锐、疲惫，对轻率的亲密保持警惕。" },
    { id: "ivors", name: "Miss Ivors", role: "朋友与质问者", note: "会直接挑战 Gabriel 对爱尔兰身份的态度。" },
    { id: "michael", name: "未知青年", role: "记忆中的人物", note: "尚未被 Gabriel 真正认识。" },
  ],
  scenes: [
    {
      id: "party",
      eyebrow: "第一幕 · 莫肯家的年度晚宴",
      title: "灯火、舞步与错误的语气",
      description: "客厅热闹，Gabriel 却不断意识到自己与他人的距离。你有四次行动机会。",
      turns: 4,
      actions: [
        {
          id: "observe_lily",
          type: "investigate",
          title: "观察 Lily 的反应",
          description: "暂时不解释自己，只留意她为何突然冷淡。",
          outcome: "你注意到 Lily 的回答并非针对一句玩笑，而像是长久失望的出口。",
          effects: { empathy: 8, tension: -2 },
          reveals: ["lily_retort"],
        },
        {
          id: "tip_lily",
          type: "emotion",
          title: "用硬币结束尴尬",
          description: "将不安包进节日礼貌里，然后迅速离开。",
          outcome: "Lily 接受了硬币，尴尬被盖住，却没有真正消失。",
          effects: { trust: -2, tension: 6 },
          reveals: ["gabriel_avoidance"],
        },
        {
          id: "listen_julia",
          type: "investigate",
          title: "认真聆听 Julia 唱歌",
          description: "不准备演讲，也不评判技巧，只听她唱完。",
          outcome: "歌声里的衰老与温柔，使你第一次感觉到今晚并非永恒。",
          effects: { empathy: 7, intimacy: 2 },
          reveals: ["julia_song"],
        },
        {
          id: "debate_ivors",
          type: "emotion",
          title: "反驳 Miss Ivors",
          description: "维护自己的生活方式，不让她定义你是谁。",
          outcome: "你赢得了几句漂亮的反驳，却让谈话变成了一场防守。",
          effects: { tension: 12, openness: -7 },
          reveals: ["ivors_conflict"],
        },
        {
          id: "ask_ivors",
          type: "investigate",
          title: "询问 Miss Ivors 为何在意",
          description: "承认自己不舒服，但请她继续说。",
          outcome: "她的指责仍然尖锐，却让你看见身份问题背后的情感重量。",
          effects: { empathy: 6, openness: 8, tension: 3 },
          reveals: ["ivors_conflict", "identity_question"],
        },
      ],
      npc: {
        calm: "Gretta 在舞曲间隙看了你一眼。她发现今晚的你比平时更愿意听。",
        tense: "Gretta 注意到你持续紧绷，选择暂时不靠近。",
      },
    },
    {
      id: "departure",
      eyebrow: "第二幕 · 晚宴结束后的楼梯",
      title: "一首歌停留在门厅",
      description: "Gretta 站在楼梯上倾听远处的歌。她仿佛突然不在这里。你有四次行动机会。",
      turns: 4,
      actions: [
        {
          id: "observe_gretta",
          type: "investigate",
          title: "观察 Gretta 的神情",
          description: "先不打断她，记住这段沉默。",
          outcome: "她并非只是感动。那首歌似乎打开了一个你从未进入的房间。",
          effects: { empathy: 7, openness: 4 },
          reveals: ["gretta_reaction"],
        },
        {
          id: "identify_song",
          type: "investigate",
          title: "询问歌曲的名字",
          description: "向歌者确认旋律与歌词。",
          outcome: "你得知这首歌叫《奥格里姆的姑娘》，关于雨、等待与失去。",
          effects: { empathy: 3 },
          reveals: ["old_song"],
        },
        {
          id: "compliment_gretta",
          type: "emotion",
          title: "称赞 Gretta 此刻很美",
          description: "试图将她从记忆中带回你们的浪漫。",
          outcome: "她微笑了，但那笑意没有完全抵达眼睛。",
          effects: { intimacy: 5, tension: 4 },
          reveals: ["gretta_distance"],
        },
        {
          id: "ask_about_song",
          type: "emotion",
          title: "问她为何被歌曲触动",
          description: "直接询问，却不要求她立刻回答。",
          outcome: "Gretta 说她想起了很久以前的一个人，但还不愿继续。",
          effects: { trust: 5, openness: 7, tension: 3 },
          reveals: ["michael_name"],
          requiresAny: ["gretta_reaction", "old_song"],
        },
        {
          id: "press_on_stairs",
          type: "emotion",
          title: "追问那个名字",
          description: "你无法忍受自己被排除在她的过去之外。",
          outcome: "Gretta 告诉了你 Michael 的名字，却因为你的逼迫变得防备。",
          effects: { openness: 4, tension: 14, trust: -8 },
          reveals: ["michael_name"],
          requires: ["michael_name"],
        },
      ],
      npc: {
        calm: "回旅馆的路上，Gretta 主动提到那首歌来自她年轻时居住的地方。",
        tense: "回旅馆的路上，Gretta 一直沉默。雪落在你们之间。",
      },
    },
    {
      id: "hotel",
      eyebrow: "第三幕 · Gresham 旅馆",
      title: "窗外的雪与无法占有的过去",
      description: "Gretta 的记忆终于来到房间里。最后四次行动将决定你们如何面对它。",
      turns: 4,
      actions: [
        {
          id: "ask_michael_gently",
          type: "emotion",
          title: "温和地询问 Michael",
          description: "告诉她，你想理解，而不是审判。",
          outcome: "Gretta 讲起那个在雨中来到窗下的青年。",
          effects: { trust: 12, openness: 14, empathy: 9, tension: -5 },
          reveals: ["rain_visit", "michael_truth"],
          requiresAny: ["michael_name", "song_hypothesis"],
        },
        {
          id: "share_insecurity",
          type: "emotion",
          title: "承认自己的嫉妒与不安",
          description: "不把不安变成指控，而是承认你的局限。",
          outcome: "Gretta 没有立即安慰你，但她不再需要防御你的愤怒。",
          effects: { trust: 9, intimacy: 8, openness: 7, tension: -4, empathy: 4 },
          reveals: ["gabriel_vulnerability"],
          requiresAny: ["self_hypothesis", "michael_name"],
        },
        {
          id: "offer_silence",
          type: "emotion",
          title: "允许她安静地悲伤",
          description: "不要求答案，只在她身边留下空间。",
          outcome: "沉默没有解决一切，却使悲伤不再需要辩护。",
          effects: { trust: 8, intimacy: 5, empathy: 12, tension: -8 },
          reveals: ["compassionate_silence"],
        },
        {
          id: "compare_love",
          type: "emotion",
          title: "追问她是否更爱 Michael",
          description: "要求过去与现在给出一个明确胜负。",
          outcome: "Gretta 的悲伤被迫变成辩护。你得到答案的碎片，却失去靠近它的方式。",
          effects: { trust: -15, intimacy: -10, tension: 22, openness: -12 },
          reveals: ["jealous_wound"],
          requires: ["michael_name"],
        },
        {
          id: "look_at_snow",
          type: "investigate",
          title: "凝视窗外的雪",
          description: "把今晚的人与远方的死者放在同一场雪中思考。",
          outcome: "你感到自己的身份短暂松动，理解不再意味着占有。",
          effects: { empathy: 15, tension: -5, openness: 6 },
          reveals: ["snow_reflection"],
        },
      ],
      npc: {
        calm: "Gretta 在睡去前握了一下你的手。她没有要求你立刻理解全部。",
        tense: "Gretta 转身睡去。你们都带着未说完的话。",
      },
    },
  ],
  clues: {
    lily_retort: { title: "Lily 的苦涩回答", kind: "testimony", character: "lily", text: "一句玩笑也可能踩中别人长期承受的重量。" },
    gabriel_avoidance: { title: "用礼貌逃离尴尬", kind: "observation", character: "gabriel", text: "Gabriel 常用礼貌动作避免面对失败的交流。" },
    julia_song: { title: "Julia 歌声中的衰老", kind: "observation", character: "gabriel", text: "欢乐之中已经存在失去与告别。" },
    ivors_conflict: { title: "与 Miss Ivors 的冲突", kind: "testimony", character: "ivors", text: "Gabriel 对身份质疑的第一反应是防守。" },
    identity_question: { title: "身份并非抽象问题", kind: "confirmed", character: "ivors", text: "文化与归属会真实影响人与人的距离。" },
    gretta_reaction: { title: "Gretta 在楼梯上的神情", kind: "observation", character: "gretta", text: "歌声触发了强烈且私密的记忆。" },
    old_song: { title: "《奥格里姆的姑娘》", kind: "confirmed", character: "gretta", text: "一首关于雨、等待与失去的旧歌。" },
    gretta_distance: { title: "没有抵达眼睛的微笑", kind: "observation", character: "gretta", text: "浪漫姿态无法替代真正理解。" },
    michael_name: { title: "Michael Furey", kind: "testimony", character: "michael", text: "Gretta 年轻时认识的一个人。" },
    rain_visit: { title: "雨中的最后探望", kind: "testimony", character: "michael", text: "Michael 在病中来到 Gretta 窗下，随后去世。" },
    michael_truth: { title: "Michael 的死亡", kind: "confirmed", character: "michael", text: "他的死亡与对 Gretta 的情感紧密相连。" },
    gabriel_vulnerability: { title: "Gabriel 承认不安", kind: "confirmed", character: "gabriel", text: "脆弱可以成为交流，而不必成为攻击。" },
    compassionate_silence: { title: "不要求解释的陪伴", kind: "confirmed", character: "gretta", text: "陪伴有时比立即获得答案更重要。" },
    jealous_wound: { title: "被迫比较的爱情", kind: "confirmed", character: "gretta", text: "将爱变成胜负会伤害当下关系。" },
    snow_reflection: { title: "落在所有人身上的雪", kind: "observation", character: "gabriel", text: "活人与死者、熟悉与陌生被同一场雪连接。" },
  },
  hypotheses: [
    {
      id: "song_hypothesis",
      title: "歌曲通往 Gretta 隐藏的过去",
      requires: ["gretta_reaction", "old_song"],
      text: "她的悲伤并非关于宴会，而是关于歌声唤醒的人。",
      effects: { empathy: 5, openness: 3 },
    },
    {
      id: "self_hypothesis",
      title: "Gabriel 的防守模式",
      requiresAnyPairs: [["lily_retort", "ivors_conflict"], ["gabriel_avoidance", "ivors_conflict"]],
      text: "当交流失控时，Gabriel 会用礼貌、知识或反驳保护自己。",
      effects: { empathy: 5, tension: -3 },
    },
    {
      id: "love_hypothesis",
      title: "理解不等于占有",
      requires: ["michael_truth", "snow_reflection"],
      text: "理解 Gretta 的过去，不需要 Gabriel 在过去中获胜。",
      effects: { empathy: 8, trust: 4 },
    },
  ],
};
